// Generated by delombok at Fri May 08 12:40:33 IST 2026
package com.portfolio.dto;

import jakarta.validation.constraints.NotBlank;

public class ProjectDto {
    private Long id;
    @NotBlank(message = "Title is required")
    private String title;
    @NotBlank(message = "Description is required")
    private String description;
    @NotBlank(message = "Tech stack is required")
    private String techStack;
    private String githubLink;
    private String liveLink;
    private String image;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProjectDto() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTechStack() {
        return this.techStack;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGithubLink() {
        return this.githubLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLiveLink() {
        return this.liveLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getImage() {
        return this.image;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTechStack(final String techStack) {
        this.techStack = techStack;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGithubLink(final String githubLink) {
        this.githubLink = githubLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLiveLink(final String liveLink) {
        this.liveLink = liveLink;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setImage(final String image) {
        this.image = image;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProjectDto)) return false;
        final ProjectDto other = (ProjectDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$techStack = this.getTechStack();
        final java.lang.Object other$techStack = other.getTechStack();
        if (this$techStack == null ? other$techStack != null : !this$techStack.equals(other$techStack)) return false;
        final java.lang.Object this$githubLink = this.getGithubLink();
        final java.lang.Object other$githubLink = other.getGithubLink();
        if (this$githubLink == null ? other$githubLink != null : !this$githubLink.equals(other$githubLink)) return false;
        final java.lang.Object this$liveLink = this.getLiveLink();
        final java.lang.Object other$liveLink = other.getLiveLink();
        if (this$liveLink == null ? other$liveLink != null : !this$liveLink.equals(other$liveLink)) return false;
        final java.lang.Object this$image = this.getImage();
        final java.lang.Object other$image = other.getImage();
        if (this$image == null ? other$image != null : !this$image.equals(other$image)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProjectDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $techStack = this.getTechStack();
        result = result * PRIME + ($techStack == null ? 43 : $techStack.hashCode());
        final java.lang.Object $githubLink = this.getGithubLink();
        result = result * PRIME + ($githubLink == null ? 43 : $githubLink.hashCode());
        final java.lang.Object $liveLink = this.getLiveLink();
        result = result * PRIME + ($liveLink == null ? 43 : $liveLink.hashCode());
        final java.lang.Object $image = this.getImage();
        result = result * PRIME + ($image == null ? 43 : $image.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProjectDto(id=" + this.getId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", techStack=" + this.getTechStack() + ", githubLink=" + this.getGithubLink() + ", liveLink=" + this.getLiveLink() + ", image=" + this.getImage() + ")";
    }
}
