// Generated by delombok at Fri May 08 12:40:33 IST 2026
package com.portfolio.dto;

public class AuthResponse {
    private String token;

    
    
    public String getToken() {
        return this.token;
    }

    
    
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.Override
    
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthResponse)) return false;
        final AuthResponse other = (AuthResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        return true;
    }

    
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthResponse;
    }

    @java.lang.Override
    
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        return result;
    }

    @java.lang.Override
    
    
    public java.lang.String toString() {
        return "AuthResponse(token=" + this.getToken() + ")";
    }

    
    
    public AuthResponse() {
    }

    
    
    public AuthResponse(final String token) {
        this.token = token;
    }
}
