// Generated by delombok at Fri May 08 12:40:34 IST 2026
package com.portfolio.dto;

import jakarta.validation.constraints.NotBlank;

public class SkillDto {
    private Long id;
    @NotBlank(message = "Skill name is required")
    private String name;
    @NotBlank(message = "Skill level is required")
    private String level;
    private String category;
    private String logo;

    
    
    public SkillDto() {
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getName() {
        return this.name;
    }

    
    
    public String getLevel() {
        return this.level;
    }

    public String getCategory() {
        return this.category;
    }

    public String getLogo() {
        return this.logo;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setName(final String name) {
        this.name = name;
    }

    
    
    public void setLevel(final String level) {
        this.level = level;
    }

    public void setCategory(final String category) {
        this.category = category;
    }

    public void setLogo(final String logo) {
        this.logo = logo;
    }

    @java.lang.Override
    
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SkillDto)) return false;
        final SkillDto other = (SkillDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$level = this.getLevel();
        final java.lang.Object other$level = other.getLevel();
        if (this$level == null ? other$level != null : !this$level.equals(other$level)) return false;
        return true;
    }

    
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SkillDto;
    }

    @java.lang.Override
    
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $level = this.getLevel();
        result = result * PRIME + ($level == null ? 43 : $level.hashCode());
        return result;
    }

    @java.lang.Override
    
    
    public java.lang.String toString() {
        return "SkillDto(id=" + this.getId() + ", name=" + this.getName() + ", level=" + this.getLevel() + ")";
    }
}
