// Generated by delombok at Fri May 08 12:40:34 IST 2026
package com.portfolio.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "blogs", indexes = {@Index(name = "idx_blog_title", columnList = "title")})
public class Blog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String title;
    @Column(columnDefinition = "LONGTEXT", nullable = false)
    private String content;
    private String image;
    private String externalLink;
    private LocalDateTime createdAt = LocalDateTime.now();

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getTitle() {
        return this.title;
    }

    
    
    public String getContent() {
        return this.content;
    }

    
    
    public String getImage() {
        return this.image;
    }

    public String getExternalLink() {
        return this.externalLink;
    }

    
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setTitle(final String title) {
        this.title = title;
    }

    
    
    public void setContent(final String content) {
        this.content = content;
    }

    
    
    public void setImage(final String image) {
        this.image = image;
    }

    public void setExternalLink(final String externalLink) {
        this.externalLink = externalLink;
    }

    
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Blog)) return false;
        final Blog other = (Blog) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$image = this.getImage();
        final java.lang.Object other$image = other.getImage();
        if (this$image == null ? other$image != null : !this$image.equals(other$image)) return false;
        final java.lang.Object this$externalLink = this.getExternalLink();
        final java.lang.Object other$externalLink = other.getExternalLink();
        if (this$externalLink == null ? other$externalLink != null : !this$externalLink.equals(other$externalLink)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Blog;
    }

    @java.lang.Override
    
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $image = this.getImage();
        result = result * PRIME + ($image == null ? 43 : $image.hashCode());
        final java.lang.Object $externalLink = this.getExternalLink();
        result = result * PRIME + ($externalLink == null ? 43 : $externalLink.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    
    
    public java.lang.String toString() {
        return "Blog(id=" + this.getId() + ", title=" + this.getTitle() + ", content=" + this.getContent() + ", image=" + this.getImage() + ", externalLink=" + this.getExternalLink() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    
    
    public Blog() {
    }

    
    
    public Blog(final Long id, final String title, final String content, final String image, final String externalLink, final LocalDateTime createdAt) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.image = image;
        this.externalLink = externalLink;
        this.createdAt = createdAt;
    }
}
