// Generated by delombok at Fri May 08 12:40:34 IST 2026
package com.portfolio.model;

import jakarta.persistence.*;

@Entity
@Table(name = "projects", indexes = {@Index(name = "idx_project_title", columnList = "title")})
public class Project {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String title;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String techStack;
    private String githubLink;
    private String liveLink;
    private String image;

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getTitle() {
        return this.title;
    }

    
    
    public String getDescription() {
        return this.description;
    }

    
    
    public String getTechStack() {
        return this.techStack;
    }

    
    
    public String getGithubLink() {
        return this.githubLink;
    }

    
    
    public String getLiveLink() {
        return this.liveLink;
    }

    
    
    public String getImage() {
        return this.image;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setTitle(final String title) {
        this.title = title;
    }

    
    
    public void setDescription(final String description) {
        this.description = description;
    }

    
    
    public void setTechStack(final String techStack) {
        this.techStack = techStack;
    }

    
    
    public void setGithubLink(final String githubLink) {
        this.githubLink = githubLink;
    }

    
    
    public void setLiveLink(final String liveLink) {
        this.liveLink = liveLink;
    }

    
    
    public void setImage(final String image) {
        this.image = image;
    }

    @java.lang.Override
    
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Project)) return false;
        final Project other = (Project) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$techStack = this.getTechStack();
        final java.lang.Object other$techStack = other.getTechStack();
        if (this$techStack == null ? other$techStack != null : !this$techStack.equals(other$techStack)) return false;
        final java.lang.Object this$githubLink = this.getGithubLink();
        final java.lang.Object other$githubLink = other.getGithubLink();
        if (this$githubLink == null ? other$githubLink != null : !this$githubLink.equals(other$githubLink)) return false;
        final java.lang.Object this$liveLink = this.getLiveLink();
        final java.lang.Object other$liveLink = other.getLiveLink();
        if (this$liveLink == null ? other$liveLink != null : !this$liveLink.equals(other$liveLink)) return false;
        final java.lang.Object this$image = this.getImage();
        final java.lang.Object other$image = other.getImage();
        if (this$image == null ? other$image != null : !this$image.equals(other$image)) return false;
        return true;
    }

    
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Project;
    }

    @java.lang.Override
    
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $techStack = this.getTechStack();
        result = result * PRIME + ($techStack == null ? 43 : $techStack.hashCode());
        final java.lang.Object $githubLink = this.getGithubLink();
        result = result * PRIME + ($githubLink == null ? 43 : $githubLink.hashCode());
        final java.lang.Object $liveLink = this.getLiveLink();
        result = result * PRIME + ($liveLink == null ? 43 : $liveLink.hashCode());
        final java.lang.Object $image = this.getImage();
        result = result * PRIME + ($image == null ? 43 : $image.hashCode());
        return result;
    }

    @java.lang.Override
    
    
    public java.lang.String toString() {
        return "Project(id=" + this.getId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", techStack=" + this.getTechStack() + ", githubLink=" + this.getGithubLink() + ", liveLink=" + this.getLiveLink() + ", image=" + this.getImage() + ")";
    }

    
    
    public Project() {
    }

    
    
    public Project(final Long id, final String title, final String description, final String techStack, final String githubLink, final String liveLink, final String image) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.techStack = techStack;
        this.githubLink = githubLink;
        this.liveLink = liveLink;
        this.image = image;
    }
}
