// Generated by delombok at Fri May 08 12:40:34 IST 2026
package com.portfolio.model;

import jakarta.persistence.*;

@Entity
@Table(name = "resumes")
public class Resume {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String fileUrl;

    
    
    public Long getId() {
        return this.id;
    }

    
    
    public String getFileUrl() {
        return this.fileUrl;
    }

    
    
    public void setId(final Long id) {
        this.id = id;
    }

    
    
    public void setFileUrl(final String fileUrl) {
        this.fileUrl = fileUrl;
    }

    @java.lang.Override
    
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Resume)) return false;
        final Resume other = (Resume) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$fileUrl = this.getFileUrl();
        final java.lang.Object other$fileUrl = other.getFileUrl();
        if (this$fileUrl == null ? other$fileUrl != null : !this$fileUrl.equals(other$fileUrl)) return false;
        return true;
    }

    
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Resume;
    }

    @java.lang.Override
    
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $fileUrl = this.getFileUrl();
        result = result * PRIME + ($fileUrl == null ? 43 : $fileUrl.hashCode());
        return result;
    }

    @java.lang.Override
    
    
    public java.lang.String toString() {
        return "Resume(id=" + this.getId() + ", fileUrl=" + this.getFileUrl() + ")";
    }

    
    
    public Resume() {
    }

    
    
    public Resume(final Long id, final String fileUrl) {
        this.id = id;
        this.fileUrl = fileUrl;
    }
}
